version: '3'
services:

  db:
    build:
      context: db
    volumes:
      - ./db/data_dump:/var/opt/mssql

  app:
    build:
      context: app
    ports:
      - 8080:8080
    depends_on:
        - db
